import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import Header from "@/components/Header";
import Nav from "@/components/Nav";
import { NavStateProvider } from "@/hooks/navState";
import { SWRConfig } from "swr";
import { fetcher } from "@/services/fetcher";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="!h-dvh w-full">
      <SWRConfig
        value={{
          refreshInterval: 3000,
          fetcher: fetcher,
        }}
      >
        <NavStateProvider>
          <body className="flex  p-5 bg-gray-100 !h-dvh">
            <Nav />

            <main className="w-full !h-dvh">
              <Header />
              <div className="scroll-auto  overflow-scroll">{children}</div>
            </main>
          </body>
        </NavStateProvider>
      </SWRConfig>
    </html>
  );
}
