import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import Header from "@/components/Header";
import Nav from "@/components/Nav";
import { NavStateProvider } from "@/hooks/navState";
import { SwrProvider } from "@/providers/SwrProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="!h-dvh w-full">
      <SwrProvider>
        <NavStateProvider>
          <body className="flex  p-5 bg-gray-100 overflow-y-hidden">
            <Nav />

            <main className="w-full max-h-screen overflow-auto ">
              <Header />
              <div className="opacity-1 ease-in-out transition-opacity duration-300 w-full">
                {children}
              </div>
            </main>
          </body>
        </NavStateProvider>
      </SwrProvider>
    </html>
  );
}
